// Complete expanded user dataset for UserManagementTable.jsx
export const expandedMockUsers = [
  {
    id: "USR001",
    employeeId: "12345",
    userId: "ALBIN001",
    merchantId: "10831",
    mobile: "9061271803",
    agentName: "Albin Shibu",
    email: "albinshibu@fibe.in",
    branchGroup: "Mumbai Central",
    categories: ["Retail", "Personal"],
    roles: ["MERCHANT_ADMIN"],
    status: "active",
    kam: "Sarah Johnson",
    password: "••••••••",
  },
  {
    id: "USR002",
    employeeId: "EMP002",
    userId: "KUSH002",
    merchantId: "1200",
    mobile: "9876543211",
    agentName: "Kush Kush",
    email: "kush@fibe.in",
    branchGroup: "Delhi North",
    categories: ["Corporate"],
    roles: ["ADMIN"],
    status: "active",
    kam: "Mike Wilson",
    password: "••••••••",
  },
  {
    id: "USR003",
    employeeId: "1190",
    userId: "SHUBH003",
    merchantId: "1010",
    mobile: "9140686575",
    agentName: "Shubhangi S",
    email: "shubhangi-s@cybersrcc.com",
    branchGroup: "Bangalore South",
    categories: ["Retail", "SME"],
    roles: ["MERCHANT_CHECKER"],
    status: "disabled",
    kam: "Lisa Davis",
    password: "••••••••",
  },
  {
    id: "USR004",
    employeeId: "espl1111",
    userId: "OPS004",
    merchantId: "1010",
    mobile: "9890437707",
    agentName: "OPS Manager",
    email: "email@fibe.in",
    branchGroup: "Chennai East",
    categories: ["Personal", "Corporate"],
    roles: ["OPS_MANAGER"],
    status: "active",
    kam: "Tom Anderson",
    password: "••••••••",
  },
  {
    id: "USR005",
    employeeId: "ESPL1111",
    userId: "AYUSH005",
    merchantId: "1010",
    mobile: "9021616118",
    agentName: "Ayush Kumbhare",
    email: "ayush.kumbhare@fibe.in",
    branchGroup: "Kolkata West",
    categories: ["SME"],
    roles: ["ES_ADMIN"],
    status: "active",
    kam: "Jane Smith",
    password: "••••••••",
  },
  {
    id: "USR006",
    employeeId: "ESPL7171",
    userId: "ANUP006",
    merchantId: "1010",
    mobile: "8600931386",
    agentName: "Anup Borde",
    email: "anup.borde@fibe.in",
    branchGroup: "Pune Central",
    categories: ["Retail"],
    roles: ["ES_ADMIN"],
    status: "active",
    kam: "Robert Johnson",
    password: "••••••••",
  },
  {
    id: "USR007",
    employeeId: "esplc2",
    userId: "BUDDHA007",
    merchantId: "1010",
    mobile: "9881516526",
    agentName: "Buddhabhushan Bhagat",
    email: "Bhuddhbhushan.Bhagat@fibe.in",
    branchGroup: "Hyderabad North",
    categories: ["Corporate", "SME"],
    roles: ["SETTLEMENT_OPS_MANAGER"],
    status: "active",
    kam: "Emma Wilson",
    password: "••••••••",
  },
  {
    id: "USR008",
    employeeId: "ESPL8888",
    userId: "KUSH008",
    merchantId: "1010",
    mobile: "9650208558",
    agentName: "Kushagra",
    email: "kushagra@cybersrcc.com",
    branchGroup: "Ahmedabad West",
    categories: ["Personal", "Retail"],
    roles: ["MERCHANT_MAKER"],
    status: "disabled",
    kam: "Chris Brown",
    password: "••••••••",
  },
  {
    id: "USR009",
    employeeId: "ESPL444",
    userId: "MAKER009",
    merchantId: "1010",
    mobile: "8217701069",
    agentName: "Maker Admin",
    email: "emailESADMIN@earlysalary.com",
    branchGroup: "Gurgaon Central",
    categories: ["Corporate", "SME", "Retail"],
    roles: ["ES_ADMIN", "MERCHANT_MAKER"],
    status: "active",
    kam: "David Lee",
    password: "••••••••",
  },
  {
    id: "USR010",
    employeeId: "EMP123",
    userId: "OMKAR010",
    merchantId: "1010",
    mobile: "6388584233",
    agentName: "Omkar Singh",
    email: "omkar@cybersrcc.com",
    branchGroup: "Noida East",
    categories: ["Personal"],
    roles: ["SETTLEMENT_OD_SUPPORT"],
    status: "active",
    kam: "Sarah Johnson",
    password: "••••••••",
  },
  {
    id: "USR011",
    employeeId: "SW232",
    userId: "VINAY011",
    merchantId: "1010",
    mobile: "8555128411",
    agentName: "Vinay Marathe",
    email: "vinay.marathe@earlysalary.com",
    branchGroup: "Mumbai West",
    categories: ["Corporate"],
    roles: ["MERCHANT_ADMIN"],
    status: "active",
    kam: "Mike Wilson",
    password: "••••••••",
  },
  {
    id: "USR012",
    employeeId: "ESP1111",
    userId: "AGENT012",
    merchantId: "7434",
    mobile: "9755562853",
    agentName: "FOS Agent",
    email: "email@gmail.com",
    branchGroup: "Delhi South",
    categories: ["SME"],
    roles: ["FOS_AGENT"],
    status: "disabled",
    kam: "Lisa Davis",
    password: "••••••••",
  },
  {
    id: "USR013",
    employeeId: "SW387",
    userId: "SUMIT013",
    merchantId: "3436",
    mobile: "7906695445",
    agentName: "Sumit Gupta",
    email: "sg02.aug@fibe.com",
    branchGroup: "Bangalore North",
    categories: ["Retail", "Personal"],
    roles: ["ADMIN"],
    status: "active",
    kam: "Tom Anderson",
    password: "••••••••",
  },
  {
    id: "USR014",
    employeeId: "EMP654",
    userId: "PRADEEP014",
    merchantId: "1010",
    mobile: "9876543212",
    agentName: "Pradeep J",
    email: "pradeeppp@es.com",
    branchGroup: "Chennai West",
    categories: ["Corporate", "SME"],
    roles: ["SALES_EXECUTIVE"],
    status: "active",
    kam: "Jane Smith",
    password: "••••••••",
  },
  {
    id: "USR015",
    employeeId: "DANISH015",
    userId: "DANISH015",
    merchantId: "1010",
    mobile: "6303674304",
    agentName: "Danish Gada",
    email: "danish.gada@earlysalary.com",
    branchGroup: "Kolkata East",
    categories: ["Personal", "Retail"],
    roles: ["SETTLEMENT_OD_SUPPORT"],
    status: "active",
    kam: "Robert Johnson",
    password: "••••••••",
  },
  {
    id: "USR016",
    employeeId: "SW250",
    userId: "ANKIT016",
    merchantId: "10470",
    mobile: "7720967019",
    agentName: "Ankit Sulinder",
    email: "Ankit.Sulinder@earlysalary.com",
    branchGroup: "Pune East",
    categories: ["Corporate"],
    roles: ["ES_ADMIN", "SUPERADMIN"],
    status: "active",
    kam: "Emma Wilson",
    password: "••••••••",
  },
  {
    id: "USR017",
    employeeId: "120",
    userId: "SUMIT017",
    merchantId: "1010",
    mobile: "7906695445",
    agentName: "Sumit Kumar",
    email: "sumit.gupta@fibe.in",
    branchGroup: "Hyderabad South",
    categories: ["SME", "Retail"],
    roles: ["ONBOARDING_OD_SUPPORT"],
    status: "disabled",
    kam: "Chris Brown",
    password: "••••••••",
  },
  {
    id: "USR018",
    employeeId: "SHREYASH018",
    userId: "SHREYASH018",
    merchantId: "7434",
    mobile: "8275729820",
    agentName: "Shreyash Kale",
    email: "shreyash.kale@earlysalary.com",
    branchGroup: "Ahmedabad North",
    categories: ["Personal"],
    roles: ["FOS_AGENT"],
    status: "active",
    kam: "David Lee",
    password: "••••••••",
  },
  {
    id: "USR019",
    employeeId: "2222",
    userId: "PAVAN019",
    merchantId: "10609",
    mobile: "8886126375",
    agentName: "Pavan Kumar",
    email: "Pavan3.kumar@upgrad.com",
    branchGroup: "Gurgaon North",
    categories: ["Corporate", "SME"],
    roles: ["MERCHANT_ADMIN"],
    status: "active",
    kam: "Sarah Johnson",
    password: "••••••••",
  },
  {
    id: "USR020",
    employeeId: "1111",
    userId: "SUDHANSHU020",
    merchantId: "10602",
    mobile: "7909008748",
    agentName: "Sudhanshu Pandey",
    email: "sudhanshu.pandey@upgrad.com",
    branchGroup: "Noida West",
    categories: ["Retail", "Personal"],
    roles: ["MERCHANT_ADMIN"],
    status: "active",
    kam: "Mike Wilson",
    password: "••••••••",
  },
  {
    id: "USR021",
    employeeId: "ESPL382",
    userId: "ASTHA021",
    merchantId: "1010",
    mobile: "7987512014",
    agentName: "Astha Lamba",
    email: "astha.lamba@earlysalary.com",
    branchGroup: "Mumbai North",
    categories: ["Corporate"],
    roles: ["ES_ADMIN"],
    status: "active",
    kam: "Lisa Davis",
    password: "••••••••",
  },
  {
    id: "USR022",
    employeeId: "ESPL303",
    userId: "AJAY022",
    merchantId: "3563",
    mobile: "9970719676",
    agentName: "Ajay Jejurkar",
    email: "ajay.j@earlysalary.com",
    branchGroup: "Delhi West",
    categories: ["SME", "Retail"],
    roles: ["ES_ADMIN"],
    status: "disabled",
    kam: "Tom Anderson",
    password: "••••••••",
  },
  {
    id: "USR023",
    employeeId: "PULKIT023",
    userId: "PULKIT023",
    merchantId: "5295",
    mobile: "8951979829",
    agentName: "Pulkit Jain",
    email: "pulkit.jain@simplilearn.net",
    branchGroup: "Bangalore Central",
    categories: ["Personal", "Corporate"],
    roles: ["MERCHANT_ADMIN"],
    status: "active",
    kam: "Jane Smith",
    password: "••••••••",
  },
  {
    id: "USR024",
    employeeId: "ES1234669",
    userId: "NIKHIL024",
    merchantId: "1010",
    mobile: "9770594287",
    agentName: "Nikhil Gayki",
    email: "nikhil.gayki@earlysalary.com",
    branchGroup: "Chennai North",
    categories: ["SME"],
    roles: ["ES_ADMIN"],
    status: "active",
    kam: "Robert Johnson",
    password: "••••••••",
  },
  {
    id: "USR025",
    employeeId: "ES1234569",
    userId: "PRIYA025",
    merchantId: "1010",
    mobile: "9770514387",
    agentName: "Priya Sharma",
    email: "priya.sharma@earlysalary.com",
    branchGroup: "Kolkata North",
    categories: ["Retail", "Personal"],
    roles: ["ES_ADMIN", "SUPERADMIN"],
    status: "active",
    kam: "Emma Wilson",
    password: "••••••••",
  },
  {
    id: "USR026",
    employeeId: "3300",
    userId: "SECURE026",
    merchantId: "1078",
    mobile: "7896523565",
    agentName: "Security Admin",
    email: "secure@earlysalary.com",
    branchGroup: "Pune North",
    categories: ["Corporate", "SME"],
    roles: ["ES_ADMIN", "SUPERADMIN"],
    status: "active",
    kam: "Chris Brown",
    password: "••••••••",
  },
  {
    id: "USR027",
    employeeId: "Checker1",
    userId: "AJINKYA027",
    merchantId: "1010",
    mobile: "7555494978",
    agentName: "Ajinkya Shewale",
    email: "ajinkya.shewale@earlysalary.com",
    branchGroup: "Hyderabad Central",
    categories: ["Personal"],
    roles: ["ES_ADMIN"],
    status: "disabled",
    kam: "David Lee",
    password: "••••••••",
  },
  {
    id: "USR028",
    employeeId: "Maker1",
    userId: "MAKER028",
    merchantId: "1010",
    mobile: "8555895114",
    agentName: "Maker User",
    email: "Maker@earlysalary.com",
    branchGroup: "Ahmedabad Central",
    categories: ["Retail", "SME"],
    roles: ["MERCHANT_MAKER"],
    status: "active",
    kam: "Sarah Johnson",
    password: "••••••••",
  },
  {
    id: "USR029",
    employeeId: "JYOTI029",
    userId: "JYOTI029",
    merchantId: "1077",
    mobile: "9876543210",
    agentName: "Jyoti R",
    email: "jyoti.r@earlysalary.com",
    branchGroup: "Gurgaon South",
    categories: ["Corporate"],
    roles: ["ADMIN"],
    status: "active",
    kam: "Mike Wilson",
    password: "••••••••",
  },
  {
    id: "USR030",
    employeeId: "SHUBHAM030",
    userId: "SHUBHAM030",
    merchantId: "1077",
    mobile: "8208044166",
    agentName: "Shubham Bhandarkar",
    email: "shubham.bhandarkar@earlysalary.com",
    branchGroup: "Noida North",
    categories: ["SME", "Personal"],
    roles: ["SUPERADMIN"],
    status: "active",
    kam: "Lisa Davis",
    password: "••••••••",
  },
  {
    id: "USR031",
    employeeId: "ES1234567",
    userId: "JYOTI031",
    merchantId: "3554",
    mobile: "9770514387",
    agentName: "Jyoti Rathore",
    email: "jyoti.rathore@earlysalary.com",
    branchGroup: "Mumbai South",
    categories: ["Retail"],
    roles: ["MERCHANT_ADMIN"],
    status: "active",
    kam: "Tom Anderson",
    password: "••••••••",
  },
  {
    id: "USR032",
    employeeId: "S1",
    userId: "S1_032",
    merchantId: "7615",
    mobile: "8555148212",
    agentName: "S1 User",
    email: "S1@earlysalary.com",
    branchGroup: "Delhi Central",
    categories: ["Corporate", "SME"],
    roles: ["MERCHANT"],
    status: "disabled",
    kam: "Jane Smith",
    password: "••••••••",
  },
  {
    id: "USR033",
    employeeId: "ESPL4",
    userId: "AGENTD033",
    merchantId: "7492",
    mobile: "9185554257",
    agentName: "Agent D",
    email: "fosagentD@earlysalary.com",
    branchGroup: "Bangalore West",
    categories: ["Personal", "Retail"],
    roles: ["BUSINESS_ADMIN"],
    status: "active",
    kam: "Robert Johnson",
    password: "••••••••",
  },
  {
    id: "USR034",
    employeeId: "V1",
    userId: "VIJAY034",
    merchantId: "7492",
    mobile: "9455556795",
    agentName: "Vijay Sen",
    email: "vijaysen@earlysalary.com",
    branchGroup: "Chennai Central",
    categories: ["SME"],
    roles: ["ES_ADMIN"],
    status: "active",
    kam: "Emma Wilson",
    password: "••••••••",
  },
  {
    id: "USR035",
    employeeId: "M1",
    userId: "MERCHANT035",
    merchantId: "1010",
    mobile: "7555241049",
    agentName: "Merchant Admin",
    email: "merchantadmin@gmail.com",
    branchGroup: "Kolkata Central",
    categories: ["Corporate"],
    roles: ["MERCHANT_ADMIN"],
    status: "active",
    kam: "Chris Brown",
    password: "••••••••",
  },
  {
    id: "USR036",
    employeeId: "NEELAM036",
    userId: "NEELAM036",
    merchantId: "1010",
    mobile: "7304888394",
    agentName: "Neelam Dhir",
    email: "neelam.dhir@earlysalary.com",
    branchGroup: "Pune West",
    categories: ["Retail", "Personal"],
    roles: ["MERCHANT_ADMIN"],
    status: "active",
    kam: "David Lee",
    password: "••••••••",
  },
  {
    id: "USR037",
    employeeId: "ESPL6",
    userId: "AGENTF037",
    merchantId: "7434",
    mobile: "9185557353",
    agentName: "Agent F",
    email: "fosagentE@earlysalary.com",
    branchGroup: "Hyderabad West",
    categories: ["SME", "Corporate"],
    roles: ["MERCHANT_ADMIN"],
    status: "disabled",
    kam: "Sarah Johnson",
    password: "••••••••",
  },
  {
    id: "USR038",
    employeeId: "ESPL3",
    userId: "AGENTC038",
    merchantId: "7434",
    mobile: "9175556112",
    agentName: "Agent C",
    email: "fosagentC@earlysalary.com",
    branchGroup: "Ahmedabad South",
    categories: ["Personal"],
    roles: ["FOS_AGENT"],
    status: "active",
    kam: "Mike Wilson",
    password: "••••••••",
  },
  {
    id: "USR039",
    employeeId: "ESPL2",
    userId: "AGENTB039",
    merchantId: "7545",
    mobile: "9175558846",
    agentName: "Agent B",
    email: "fosagentB@earlysalary.com",
    branchGroup: "Gurgaon West",
    categories: ["Retail", "SME"],
    roles: ["FOS_AGENT"],
    status: "active",
    kam: "Lisa Davis",
    password: "••••••••",
  },
  {
    id: "USR040",
    employeeId: "ESPL1",
    userId: "AGENTA040",
    merchantId: "7434",
    mobile: "9195555447",
    agentName: "Agent A",
    email: "fosagentA@earlysalary.com",
    branchGroup: "Noida Central",
    categories: ["Corporate", "Personal"],
    roles: ["FOS_AGENT"],
    status: "active",
    kam: "Tom Anderson",
    password: "••••••••",
  },
];
